MODULE=serial_transmitter
SRC_DIR=../..
DEPENDENCIES= \
	alu \
	alu/comparator \
	core_id_module \
	core \
	block_ram/block_ram \
	block_ram/block_ram_tdp \
	constants_rom \
	best_nonce_module \
	serial_module \
	serial_module/serial_transmitter \
	serial_module/serial_receiver \
	nonce_module \
	base64encoder/base64encoder \
	base64encoder/base64encoder_x6 \

include $(SRC_DIR)/module.mk
